name: "experiment"
on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: brew
        run: |
            brew developer on
            brew bump-formula-pr -n --no-audit \
            --url=https://registry.npmjs.org/action-docs/-/action-docs-2.5.1.tgz \
            --sha256=jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA \
            action-docs
