name: 'dependabot-auto-merge'
on:
  pull_request:
    
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

  build: 
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:

      - name: Get installation token
        uses: npalm/action-app-token@v1.0.0
        id: app-token
        with:
          appId: ${{ secrets.APP_ID }}
          appPrivateKeyBase64: ${{ secrets.APP_PRIVATE_KEY_BASE64 }}
          appInstallationType: repo
          appInstallationValue: ${{ github.repository }}

      - name: Auto merge dependabot
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ steps.app-token.outputs.token }}


# if: github.actor == 'dependabot[bot]'
#     steps:
#       - name: automerge
#         uses: actions/github-script@0.2.0
#         with:
#           script: |
#             github.pullRequests.createReview({
#               owner: context.payload.repository.owner.login,
#               repo: context.payload.repository.name,
#               pull_number: context.payload.pull_request.number,
#               event: 'APPROVE'
#             })
#             github.pullRequests.merge({
#               owner: context.payload.repository.owner.login,
#               repo: context.payload.repository.name,
#               pull_number: context.payload.pull_request.number
#             })
#           github-token: ${{github.token}}
